# SwiftLint Configuration for OS One
# https://github.com/realm/SwiftLint

# Included paths
included:
  - OS One
  - OS One Tests
  - OS One UI Tests

# Excluded paths
excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - vendor
  - scripts

# Disabled rules
disabled_rules:
  - trailing_whitespace  # Handled by formatter
  - unused_closure_parameter  # Sometimes intentional
  - nesting  # Allow nested types for organization

# Opt-in rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Rule configurations

line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 300
  error: 500

large_tuple:
  warning: 3
  error: 4

cyclomatic_complexity:
  warning: 15
  error: 25

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - i
    - j
    - x
    - y
    - z
    - db
    - url
    - URL
    - tts
    - vad
    - llm
    - stt
    - ui
    - UX

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - AI
    - LLM
    - VAD
    - TTS
    - STT
    - UI
    - UX

# Custom rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: '\bprint\('
    match_kinds:
      - identifier
    message: "Use os.log instead of print for logging"
    severity: warning

  no_force_try:
    name: "No Force Try"
    regex: 'try!'
    message: "Avoid using try! - handle errors properly"
    severity: error

  no_force_cast:
    name: "No Force Cast"
    regex: 'as!'
    message: "Avoid using as! - use conditional casting (as?) instead"
    severity: error

  double_space:
    name: "Double Space"
    regex: '([a-z,A-Z] \s+)'
    message: "Remove extra whitespace"
    severity: warning

# Reporter
reporter: "xcode"  # or "json", "csv", "checkstyle", "junit", "html", "emoji"
